# Generated by Django 3.1.7 on 2021-03-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210228_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoints',
            name='meters_id',
        ),
        migrations.AlterField(
            model_name='microgrid',
            name='microgrid_id',
            field=models.IntegerField(unique=True),
        ),
    ]
